# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Swift development targets Ubuntu 15.10
  config.vm.box = "https://cloud-images.ubuntu.com/vagrant/wily/current/wily-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.define "swift-Holle-World" do |swiftHolleWorld|
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = "swift-Holle-World"
    # Building swift requires significant resources
    vb.memory = "6144"
    vb.cpus = 4
  end

  # Prevents "stdin: is not a tty" on Ubuntu (https://github.com/mitchellh/vagrant/issues/1673)
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end

  # Initialise development environment
  config.vm.provision "shell", inline: <<-SHELL

    echo "Install required dependencies..."
    sudo DEBIAN_FRONTEND=noninteractive apt-get install clang libicu-dev

    cd /

    echo "Download swift..."
    wget -c https://swift.org/builds/swift-2.2.1-release/ubuntu1510/swift-2.2.1-RELEASE/swift-2.2.1-RELEASE-ubuntu15.10.tar.gz -O swift.tar.gz

    echo "Installing swift..."

    sudo DEBIAN_FRONTEND=noninteractive tar xzf swift.tar.gz
    sudo DEBIAN_FRONTEND=noninteractive mv swift-2.2.1-RELEASE-ubuntu15.10 swift

    echo "Finished setting up development environment - run 'vagrant ssh' to connect,"
    echo "then - run 'echo \"export PATH=/swift/usr/bin:\$PATH\" >> ~/.bashrc && . ~/.bashrc' "
  SHELL
end
